-- ============================================================
-- SUPABASE SQL DATABASE SCHEMA FOR STYLISH SALON APPLICATION
-- ============================================================
-- Execute this script in your Supabase SQL Editor (https://supabase.com)
-- ============================================================

-- 1. Create Salon Settings Table
CREATE TABLE IF NOT EXISTS public.salon_settings (
    id BIGINT PRIMARY KEY DEFAULT 1,
    salon_name TEXT NOT NULL DEFAULT 'Stylish Salon',
    owner_name TEXT NOT NULL DEFAULT 'Owner',
    currency_symbol TEXT NOT NULL DEFAULT 'PKR',
    working_hours TEXT NOT NULL DEFAULT '9:00 AM - 10:00 PM',
    theme TEXT NOT NULL DEFAULT 'LIGHT',
    language TEXT NOT NULL DEFAULT 'URDU',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.salon_settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public full access salon_settings" ON public.salon_settings FOR ALL USING (true);

-- Insert Default Row if empty
INSERT INTO public.salon_settings (id, salon_name, owner_name, currency_symbol, working_hours, theme, language)
VALUES (1, 'Stylish Salon', 'Salon Owner', 'PKR', '9:00 AM - 10:00 PM', 'LIGHT', 'URDU')
ON CONFLICT (id) DO NOTHING;


-- 2. Create Employees Table
CREATE TABLE IF NOT EXISTS public.employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'Stylist',
    phone TEXT DEFAULT '',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.employees ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public full access employees" ON public.employees FOR ALL USING (true);


-- 3. Create Daily Income / Employee Entries Table
CREATE TABLE IF NOT EXISTS public.daily_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES public.employees(id) ON DELETE CASCADE,
    employee_name TEXT NOT NULL,
    entry_date TEXT NOT NULL, -- Format: YYYY-MM-DD
    cash_earnings DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    online_payments DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    total_income DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    amount_breakdown TEXT DEFAULT '', -- Multiple amounts breakdown, e.g. "200,400,700"
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.daily_entries ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public full access daily_entries" ON public.daily_entries FOR ALL USING (true);


-- 4. Create Expenses Table
CREATE TABLE IF NOT EXISTS public.expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL DEFAULT 'Tea',
    amount DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    expense_date TEXT NOT NULL, -- Format: YYYY-MM-DD
    notes TEXT DEFAULT '',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public full access expenses" ON public.expenses FOR ALL USING (true);


-- ============================================================
-- API ACCESS & API KEY INSTRUCTIONS FOR SUPABASE
-- ============================================================
-- 1. Go to your Supabase Project Settings -> API.
-- 2. Copy your "Project URL" and "anon / public Key" or "service_role Key".
-- 3. In AI Studio Secrets or your .env file, specify:
--    SUPABASE_URL=https://your-project.supabase.co
--    SUPABASE_KEY=your-anon-or-service-role-key
-- ============================================================
