package com.example.utils

enum class Language(val code: String, val displayName: String) {
    ENGLISH("EN", "English"),
    URDU("UR", "اردو"),
    ARABIC("AR", "العربية")
}

object Strings {
    private val en = mapOf(
        "app_name" to "Salon Register",
        "nav_home" to "Home",
        "nav_analysis" to "Analysis",
        "nav_employees" to "Employees",
        "nav_expenses" to "Expenses",
        "nav_reports" to "Reports",
        "nav_settings" to "Settings",
        
        "setup_title" to "Welcome to Salon Register",
        "setup_subtitle" to "Set up your salon register in 30 seconds",
        "setup_salon_name" to "Salon / Barbershop Name",
        "setup_owner_name" to "Owner Name",
        "setup_currency" to "Preferred Currency",
        "setup_hours" to "Working Hours",
        "setup_start" to "Get Started",
        
        "today_revenue" to "Today's Revenue",
        "cash_revenue" to "Cash Payments",
        "online_revenue" to "Online Payments",
        "today_expenses" to "Today's Expenses",
        "today_profit" to "Net Profit",
        "total_revenue" to "Total Revenue",
        "quick_entry" to "Quick Daily Register",
        
        "cash_earnings" to "Cash Earnings",
        "online_payments" to "Online Payments",
        "add_amount" to "Add Amount",
        "calculate_total" to "Calculate Total Income",
        "added_amounts" to "Added Amounts",
        "enter_amount" to "Enter Amount (e.g. 200, 400)",
        "clear_all" to "Clear All",
        "total_calculated" to "Total Calculated",
        "add_employee" to "Add Employee",
        "edit_employee" to "Edit Employee",
        "remove_employee" to "Delete Employee",
        "employee_name" to "Employee Name",
        "employee_role" to "Role / Position",
        "employee_phone" to "Phone Number",
        "employee_status" to "Status",
        "enabled" to "Active",
        "disabled" to "Disabled",
        
        "expenses" to "Daily Expenses",
        "add_expense" to "Add Expense",
        "expense_name" to "Expense Name",
        "expense_category" to "Category",
        "expense_amount" to "Amount",
        "expense_notes" to "Notes (Optional)",
        
        "cat_food" to "Food",
        "cat_drinks" to "Drinks",
        "cat_tea" to "Tea",
        "cat_coffee" to "Coffee",
        "cat_electricity" to "Electricity",
        "cat_cleaning" to "Cleaning Supplies",
        "cat_products" to "Hair Products",
        "cat_repair" to "Equipment Repair",
        "cat_misc" to "Miscellaneous",
        
        "voice_title" to "Voice Command Entry",
        "voice_listening" to "Listening... Speak now",
        "voice_hint" to "Speak naturally: e.g. 'Ahmed earned 4500' or 'Tea expense 350'",
        "voice_success" to "Parsed: ",
        "voice_failed" to "Could not parse voice entry. Try again.",
        
        "analytics_title" to "Business Performance",
        "highest_earner" to "Highest Earner",
        "lowest_earner" to "Lowest Earner",
        "avg_earnings" to "Avg. per Employee",
        "payment_split" to "Cash vs Online Split",
        "category_breakdown" to "Expense Breakdown",
        "employee_performance" to "Employee Earnings",
        "revenue_trend" to "Revenue & Profit Trend",
        "no_data" to "No Data Available",
        "no_data_subtitle" to "Start entering daily earnings or expenses to see real-time analytics.",
        
        "reports_title" to "Reports & Exports",
        "daily" to "Daily",
        "weekly" to "Weekly",
        "monthly" to "Monthly",
        "yearly" to "Yearly",
        "export_pdf" to "Export PDF Statement",
        "export_csv" to "Export Excel / CSV",
        "share_report" to "Share Report",
        "report_generated" to "Report generated successfully!",
        
        "settings_title" to "Settings & Preferences",
        "salon_details" to "Salon Information",
        "appearance" to "Appearance & Theme",
        "theme_light" to "Light Theme",
        "theme_dark" to "Dark Theme",
        "theme_system" to "System Default",
        "language" to "Application Language",
        "backup_restore" to "Backup & Restore Data",
        "backup_json" to "Export JSON Backup",
        "restore_json" to "Restore JSON Backup",
        "security_roles" to "Security & Roles",
        "current_role" to "Logged in as Owner (Full Access)",
        "backup_completed" to "Backup saved successfully!",
        "restore_completed" to "Data restored successfully!",
        "about" to "About Application",
        
        "save" to "Save",
        "cancel" to "Cancel",
        "delete" to "Delete",
        "confirm" to "Confirm",
        "search" to "Search...",
        "all" to "All",
        "footer_text" to "Made by AR Words"
    )

    private val ur = mapOf(
        "app_name" to "سیلون رجسٹر",
        "nav_home" to "ہوم",
        "nav_analysis" to "تجزیہ",
        "nav_employees" to "ملازمین",
        "nav_expenses" to "اخراجات",
        "nav_reports" to "رپورٹس",
        "nav_settings" to "سیٹنگز",
        
        "setup_title" to "سیلون رجسٹر میں خوش آمدید",
        "setup_subtitle" to "30 سیکنڈ میں اپنا سیلون رجسٹر مرتب کریں",
        "setup_salon_name" to "سیلون / دکان کا نام",
        "setup_owner_name" to "مالک کا نام",
        "setup_currency" to "کرنسی کا انتخاب",
        "setup_hours" to "کام کے اوقات",
        "setup_start" to "شروع کریں",
        
        "today_revenue" to "آج کی کل آمدن",
        "cash_revenue" to "نقد آمدن",
        "online_revenue" to "آن لائن ادائیگی",
        "today_expenses" to "آج کے اخراجات",
        "today_profit" to "خالص منافع",
        "total_revenue" to "کل آمدنی",
        "quick_entry" to "روزانہ رجسٹر درج کریں",
        
        "cash_earnings" to "نقد کمائی",
        "online_payments" to "آن لائن ادائیگی",
        "add_amount" to "رقم شامل کریں",
        "calculate_total" to "کل آمدن کا حساب لگائیں",
        "added_amounts" to "شامل کردہ رقمیں",
        "enter_amount" to "رقم درج کریں (مثلاً 200، 400)",
        "clear_all" to "تمام صاف کریں",
        "total_calculated" to "کل آمدن معلوم ہو گئی",
        "add_employee" to "نیا ملازم شامل کریں",
        "edit_employee" to "ملازم کی تبدیلی",
        "remove_employee" to "ملازم کو حذف کریں",
        "employee_name" to "ملازم کا نام",
        "employee_role" to "عہدہ",
        "employee_phone" to "فون نمبر",
        "employee_status" to "حالت",
        "enabled" to "فعال",
        "disabled" to "غیر فعال",
        
        "expenses" to "روزانہ کے اخراجات",
        "add_expense" to "خرچہ شامل کریں",
        "expense_name" to "خرچے کا نام",
        "expense_category" to "قسم",
        "expense_amount" to "رقم",
        "expense_notes" to "تفصیل (اختیاری)",
        
        "cat_food" to "کھانا",
        "cat_drinks" to "مشروبات",
        "cat_tea" to "چائے",
        "cat_coffee" to "کافی",
        "cat_electricity" to "بجلی کا بل",
        "cat_cleaning" to "صفائی کا سامان",
        "cat_products" to "ہیئر پروڈکٹس",
        "cat_repair" to "سامان کی مرمت",
        "cat_misc" to "دیگر اخراجات",
        
        "voice_title" to "آواز کے ذریعے اندراج",
        "voice_listening" to "سن رہا ہے... بولیں",
        "voice_hint" to "بولیں: مثلاً 'احمد نے 4500 کمائے' یا 'چائے خرچہ 350'",
        "voice_success" to "درج ہو گیا: ",
        "voice_failed" to "آواز سمجھ نہیں آئی۔ دوبارہ کوشش کریں۔",
        
        "analytics_title" to "کاروباری کارکردگی",
        "highest_earner" to "سب سے زیادہ کمائی",
        "lowest_earner" to "کم ترین کمائی",
        "avg_earnings" to "اوسط کمائی",
        "payment_split" to "نقد بمقابلہ آن لائن",
        "category_breakdown" to "اخراجات کی تقسیم",
        "employee_performance" to "ملازمین کی کارکردگی",
        "revenue_trend" to "آمدن کا رجحان",
        "no_data" to "کوئی ڈیٹا دستیاب نہیں",
        "no_data_subtitle" to "حقیقی وقت کے تجزیے دیکھنے کے لیے کمائی یا اخراجات درج کریں۔",
        
        "reports_title" to "رپورٹس اور برآمد",
        "daily" to "روزانہ",
        "weekly" to "ہفتہ وار",
        "monthly" to "ماہانہ",
        "yearly" to "سالانہ",
        "export_pdf" to "پی ڈی ایف کی برآمد",
        "export_csv" to "ایکسل / سی ایس وی برآمد",
        "share_report" to "رپورٹ شیئر کریں",
        "report_generated" to "رپورٹ کامیابی سے تیار ہو گئی!",
        
        "settings_title" to "سیٹنگز اور ترجیحات",
        "salon_details" to "سیلون کی معلومات",
        "appearance" to "تھیم اور ظاہری شکل",
        "theme_light" to "لائٹ تھیم",
        "theme_dark" to "ڈارک تھیم",
        "theme_system" to "سسٹم ڈیفالٹ",
        "language" to "ایپلی کیشن کی زبان",
        "backup_restore" to "ڈیٹا کا بیک اپ اور بحالی",
        "backup_json" to "بیک اپ فائل تیار کریں",
        "restore_json" to "ڈیٹا بحال کریں",
        "security_roles" to "سیکیورٹی اور اختیارات",
        "current_role" to "مالک کے طور پر لاگ ان ہیں (مکمل رسائی)",
        "backup_completed" to "بیک اپ کامیابی سے محفوظ ہو گیا!",
        "restore_completed" to "ڈیٹا کامیابی سے بحال ہو گیا!",
        "about" to "ایپ کے بارے میں",
        
        "save" to "محفوظ کریں",
        "cancel" to "منسوخ",
        "delete" to "حذف کریں",
        "confirm" to "تصدیق کریں",
        "search" to "تلاش کریں...",
        "all" to "تمام",
        "footer_text" to "Made by AR Words"
    )

    private val ar = mapOf(
        "app_name" to "سجل الصالون",
        "nav_home" to "الرئيسية",
        "nav_analysis" to "التحليلات",
        "nav_employees" to "الموظفون",
        "nav_expenses" to "المصروفات",
        "nav_reports" to "التقارير",
        "nav_settings" to "الإعدادات",
        
        "setup_title" to "مرحباً بك في سجل الصالون",
        "setup_subtitle" to "قم بإعداد سجل صالونك خلال 30 ثانية",
        "setup_salon_name" to "اسم الصالون / الحلاقة",
        "setup_owner_name" to "اسم المالك",
        "setup_currency" to "العملة المفضلة",
        "setup_hours" to "ساعات العمل",
        "setup_start" to "ابدأ الآن",
        
        "today_revenue" to "إيراد اليوم",
        "cash_revenue" to "الدفع النقدي",
        "online_revenue" to "الدفع الإلكتروني",
        "today_expenses" to "مصروفات اليوم",
        "today_profit" to "صافي الربح",
        "total_revenue" to "إجمالي الإيرادات",
        "quick_entry" to "التسجيل اليومي السريع",
        
        "cash_earnings" to "الأرباح النقدية",
        "online_payments" to "المدفوعات عبر الإنترنت",
        "add_amount" to "إضافة مبلغ",
        "calculate_total" to "حساب إجمالي الدخل",
        "added_amounts" to "المبالغ المضافة",
        "enter_amount" to "أدخل المبلغ (مثلاً 200، 400)",
        "clear_all" to "مسح الكل",
        "total_calculated" to "تم حساب الإجمالي",
        "add_employee" to "إضافة موظف",
        "edit_employee" to "تعديل الموظف",
        "remove_employee" to "حذف الموظف",
        "employee_name" to "اسم الموظف",
        "employee_role" to "المسمى الوظيفي",
        "employee_phone" to "رقم الهاتف",
        "employee_status" to "الحالة",
        "enabled" to "نشط",
        "disabled" to "معطل",
        
        "expenses" to "المصروفات اليومية",
        "add_expense" to "إضافة مصروف",
        "expense_name" to "اسم المصروف",
        "expense_category" to "الفئة",
        "expense_amount" to "المبلغ",
        "expense_notes" to "ملاحظات (اختياري)",
        
        "cat_food" to "طعام",
        "cat_drinks" to "مشروبات",
        "cat_tea" to "شاي",
        "cat_coffee" to "قهوة",
        "cat_electricity" to "كهرباء",
        "cat_cleaning" to "أدوات تنظيف",
        "cat_products" to "منتجات الشعر",
        "cat_repair" to "صيانة معدات",
        "cat_misc" to "مصروفات متنوعة",
        
        "voice_title" to "الإدخال الصوتي",
        "voice_listening" to "جاري الاستماع... تحدث الآن",
        "voice_hint" to "تحدث بشكل طبيعي: مثلاً 'أحمد 4500' أو 'مصروف الشاي 350'",
        "voice_success" to "تم التسجيل: ",
        "voice_failed" to "تعذر فهم الصوت. حاول مرة أخرى.",
        
        "analytics_title" to "أداء الأعمال",
        "highest_earner" to "الأعلى إيراداً",
        "lowest_earner" to "الأقل إيراداً",
        "avg_earnings" to "متوسط الموظف",
        "payment_split" to "توزيع نقدي / إلكتروني",
        "category_breakdown" to "توزيع المصروفات",
        "employee_performance" to "أداء الموظفين",
        "revenue_trend" to "اتجاه الإيرادات",
        "no_data" to "لا توجد بيانات متاحة",
        "no_data_subtitle" to "ابدأ بإدخال الإيرادات أو المصروفات لعرض التحليلات المباشرة.",
        
        "reports_title" to "التقارير والتصدير",
        "daily" to "يومي",
        "weekly" to "أسبوعي",
        "monthly" to "شهري",
        "yearly" to "سنوي",
        "export_pdf" to "تصدير تقرير PDF",
        "export_csv" to "تصدير إكسيل / CSV",
        "share_report" to "مشاركة التقرير",
        "report_generated" to "تم إنشاء التقرير بنجاح!",
        
        "settings_title" to "الإعدادات والتفضيلات",
        "salon_details" to "معلومات الصالون",
        "appearance" to "المظهر والنسق",
        "theme_light" to "المظهر الفاتح",
        "theme_dark" to "المظهر الداكن",
        "theme_system" to "افتراضي النظام",
        "language" to "لغة التطبيق",
        "backup_restore" to "النسخ الاحتياطي والاستعادة",
        "backup_json" to "تصدير نسخة احتياطية",
        "restore_json" to "استعادة البيانات",
        "security_roles" to "الأمان والأدوار",
        "current_role" to "مسجل كمالك (صلاحيات كاملة)",
        "backup_completed" to "تم حفظ النسخة الاحتياطية بنجاح!",
        "restore_completed" to "تمت استعادة البيانات بنجاح!",
        "about" to "عن التطبيق",
        
        "save" to "حفظ",
        "cancel" to "إلغاء",
        "delete" to "حذف",
        "confirm" to "تأكيد",
        "search" to "بحث...",
        "all" to "الكل",
        "footer_text" to "Made by AR Words"
    )

    fun get(key: String, lang: String = "EN"): String {
        val dictionary = when (lang.uppercase()) {
            "UR" -> ur
            "AR" -> ar
            else -> en
        }
        return dictionary[key] ?: en[key] ?: key
    }
}
